wsr getting better

diff --git a/Scripts/wsr_create b/Scripts/wsr_create
--- a/Scripts/wsr_create
+++ b/Scripts/wsr_create
@@ -1,5 +1,5 @@
 #!/bin/sh
-
+set -e
 # PURPOSE OF THIS SCRIPT
 # This script is meant to speed up the weekly process of creating a WSR or similar texts.
 # Especially users who maintain a remote wiki for those documents should profit. 
@@ -64,13 +64,13 @@ wiki="https://gitlab.vpn.cyberus-technology.de/$gitlab_name/$repository_name/-/w
 # Include a link to the remote wiki in your WSR email
 # true = include it
 # false = don't include it
-GITLAB_LINK=false
+GITLAB_LINK=true
 
 # Once you leave the editor and the email is opend it is assumed, that your next step in the shell is to push the newly added file to your remote wiki repository.
 # Additinaly it is assumed that the link that was included in the email is of no need in the wiki and so the script attempts to remove the line containing the link before you push it to the remote wiki repository.
 # true = remove the link in the WSR file
 # false = don't remove the link in the WSR file 
-ASK_TO_REMOVE_LINK=false
+ASK_TO_REMOVE_LINK=true
 
 # Right before the script is done - head to your local wiki repository.
 # you immediately wanna push your changes to the remote wiki repository (adds target of the link included in the file)
@@ -85,10 +85,9 @@ OPEN_HOME_FILE=true
 ### Execution starts - The following code you should not need to touch
 ###
 
-echo "Please type the name of the WSR file to be created. Or press ENTER to use the default name./n
+echo "Please type the name of the WSR file to be created aka openend in case the file already exists.\nPress ENTER to use the default name.\n
 (default name: $default_file_name)"
 read -r custom_file_name
-custom_file_name="$(echo "$custom_file_name" | sed -i "s/[ \t]*$//")"
 
 if test -z "$custom_file_name" ; then
     file_name="$default_file_name"
@@ -96,7 +95,6 @@ else
     file_name="$custom_file_name"
 fi
 
-file_name="$(echo "$file_name" | sed -i "s/[ \t]*$//")"
 
 if test -f "$local_directory/$file_name"; then
     file_existed_before=true
@@ -150,32 +148,30 @@ $name"
 ### The following code you should not need to touch but in the case of tweaking the position of the link. 
 ###
 
-addToWSR greeting
+addToWSR "$(greeting)"
 
 addToWSRWhenConditionTrue "$link_to_file" "$GITLAB_LINK"
 
-addToWSR remainingMessage
+addToWSR "$(remainingMessage)"
 
 "$editor" "$local_directory/$file_name"
 
 done_edditing(){
-    echo "Are you done making changes to the file and ready to create the email sketch?/n
-    Please type y or n"
+    echo "Are you done making changes to the file and ready to create the email sketch?
+Please type y or n"
     read -r answer_done_edditing_question
-
-    answer_done_edditing_question="$(echo "$answer_done_edditing_question" | sed -i "s/[ \t]*$//")"
 
     case "$answer_done_edditing_question" in
         y)
             #thunderbird -compose "subject='$file_name',to='team@cyberus-technology.de',body='$(cat "$local_directory/$file_name")'"&
 
             if "$CD_AFTER_EDDITING"; then
-                cd "$(dirname "$wiki_home_file")" || echo "couldn't access wiki home file local directory" ; return 1
+                cd "$(dirname "$wiki_home_file")" || echo "couldn't access wiki home file local directory" ; return 12
             fi
 
             if "$ASK_TO_REMOVE_LINK"; then
                 ask_user(){
-                    echo "Do you wanna remove the link to the wiki from the local file?/n
+                    echo "Do you wanna remove the link to the wiki from the local file?\n
                     Please type y or n"
                     read -r answer_on_question_to_remove_link
 
@@ -196,14 +192,14 @@ done_edditing(){
             fi
 
             if "$OPEN_HOME_FILE"; then
-                xclip -sel c "[$file_name]()" || echo "Please install xclip to use that functionality" ; return 1
+                xclip -sel c "[$file_name]()" || echo "Please install xclip to use that functionality" ; return 15
                 "$editor" "$wiki_home_file"
             fi
             ;;
         n)
             ;;
         *)
-            ask_user;;
+            done_edditing;;
     esac
 }
 done_edditing
