improved wsr

diff --git a/Scripts/wsr_create b/Scripts/wsr_create
--- a/Scripts/wsr_create
+++ b/Scripts/wsr_create
@@ -3,7 +3,7 @@ set -e
 # PURPOSE OF THIS SCRIPT
 # This script is meant to speed up the weekly process of creating a WSR or similar texts.
 # Especially users who maintain a remote wiki for those documents should profit. 
-# For a user who is only focused on writing an email this script will still spare him some seconds but might be a slight over kill.
+# For a user who is only focused on writing an email this script should not benefit him.
 # 
 # This script creates a WSR file, opens an editor, on close of the editor an email is sketched and help for maintaining the remote wiki repository is offered.
 #
@@ -25,17 +25,18 @@ name="Marvin"
 ###
 
 
-#Path where the WSR file is created. Potentially the path to the local wiki repository
-local_directory="."
+#Path where the local wiki repository is stored
+local_wiki_repository="$HOME/Projects/wsr.wiki"
 
-#Path to the home file of my wiki 
-wiki_home_file="./home"
+#Relativ Path to $local_directory were the WSR file should be stored
+path_wsr_file_directory="."
 
 #Path to the editor to use
-editor=/bin/vim
+editor=typora
 
-#The default name for the WSR file is set to the following
+#The default structure of the WSR file
 default_file_name="$(date +"WSR%G-W%U")"
+default_file_name_extension="md"
 
 
 ###
@@ -53,7 +54,7 @@ repository_name="wsr"
 
 #Only used when Option GITLAB_LINK is set to true...
 #Path to the remote wiki repository
-wiki="https://gitlab.vpn.cyberus-technology.de/$gitlab_name/$repository_name/-/wikis"
+remote_wiki="https://gitlab.vpn.cyberus-technology.de/$gitlab_name/$repository_name/-/wikis"
 
 
 ###
@@ -78,15 +79,14 @@ ASK_TO_REMOVE_LINK=true
 # false = doesn't change the shell's current location
 CD_AFTER_EDDITING=true
 
-OPEN_HOME_FILE=true
+CP_AND_OPEN_HOME_FILE=true
 
 
 ###
 ### Execution starts - The following code you should not need to touch
 ###
 
-echo "Please type the name of the WSR file to be created aka openend in case the file already exists.\nPress ENTER to use the default name.\n
-(default name: $default_file_name)"
+echo "Please type the name of the WSR file to be created aka openend in case the file already exists.\n Please note the default_file_name_extension will be added automatically.\nPress ENTER to use the default name.\n(default name: $default_file_name)"
 read -r custom_file_name
 
 if test -z "$custom_file_name" ; then
@@ -96,7 +96,7 @@ else
 fi
 
 
-if test -f "$local_directory/$file_name"; then
+if test -f "$local_wiki_repository/$path_wsr_file_directory/$file_name$default_file_name_extension"; then
     file_existed_before=true
 else
     file_existed_before=false
@@ -107,7 +107,7 @@ link_to_file="$wiki/$(echo "$file_name" | sed "s/\s\+/%/g")"
 addToWSR(){
     if ! "$file_existed_before"; then
         text="$1"
-        echo "$text" >> "$local_directory/$file_name"
+        echo "$text" >> "$local_wiki_repository/$path_wsr_file_directory/$file_name$default_file_name_extension"
     fi
 }
 
@@ -116,7 +116,7 @@ addToWSRWhenConditionTrue(){
         text="$1"
         condition="$2"
         if "$condition" ; then
-            echo "$text" >> "$local_directory/$file_name"
+            echo "$text" >> "$local_wiki_repository/$path_wsr_file_directory/$file_name$default_file_name_extension"
         fi
     fi
 }
@@ -154,11 +154,10 @@ addToWSRWhenConditionTrue "$link_to_file" "$GITLAB_LINK"
 
 addToWSR "$(remainingMessage)"
 
-"$editor" "$local_directory/$file_name"
+"$editor" "$local_wiki_repository/$path_wsr_file_directory/$file_name$default_file_name_extension"
 
 done_edditing(){
-    echo "Are you done making changes to the file and ready to create the email sketch?
-Please type y or n"
+    echo "Are you done making changes to the file and ready to create the email sketch?\nPlease type y or n"
     read -r answer_done_edditing_question
 
     case "$answer_done_edditing_question" in
@@ -166,22 +165,18 @@ Please type y or n"
             #thunderbird -compose "subject='$file_name',to='team@cyberus-technology.de',body='$(cat "$local_directory/$file_name")'"&
 
             if "$CD_AFTER_EDDITING"; then
-                cd "$(dirname "$wiki_home_file")" || echo "couldn't access wiki home file local directory" ; return 12
+                cd "$local_wiki_repository" || echo "couldn't access local wiki repository"
             fi
 
             if "$ASK_TO_REMOVE_LINK"; then
                 ask_user(){
-                    echo "Do you wanna remove the link to the wiki from the local file?\n
-                    Please type y or n"
+                    echo "Do you wanna remove the link to the wiki from the local file?\nPlease type y or n"
                     read -r answer_on_question_to_remove_link
-
-                    answer_on_question_to_remove_link="$(echo "$answer_on_question_to_remove_link" | sed -i "s/[ \t]*$//")"
 
                     case "$answer_on_question_to_remove_link" in
                         y)
-                            tmpfile=$(mktemp /tmp/abc-script.XXXXXX)
-                            sed -i "/$link_to_file/d" "$tmpfile" 
-                            echo tmpfile > "$local_directory/$file_name" ;;
+                            sed -i "/$link_to_file/d" "$local_wiki_repository/$path_wsr_file_directory/$file_name$default_file_name_extension" || echo nano
+                            ;;
                         n)
                             ;;
                         *)
@@ -191,9 +186,9 @@ Please type y or n"
                 ask_user
             fi
 
-            if "$OPEN_HOME_FILE"; then
-                xclip -sel c "[$file_name]()" || echo "Please install xclip to use that functionality" ; return 15
-                "$editor" "$wiki_home_file"
+            if "$CP_AND_OPEN_HOME_FILE"; then
+                echo "[$file_name]($path_wsr_file_directory/$file_name)" | xclip -sel c || echo "Please check if you installed xclip"
+                "$editor" "$local_wiki_repository/home.md"
             fi
             ;;
         n)
